name: angular_sentry
description: Helper to implements sentry with Angular
version: 0.0.2
homepage: https://lefty.io
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  angular: ^4.0.0
  sentry: ^0.0.6
  stack_trace: ^1.9.0
  logging: ^0.11.0
  http: ^0.11.3

#dev_dependencies:
#  test: ^0.12.0
