name: angular_sentry
description: Helper to implements sentry with Angular
version: 0.1.0
homepage: https://lefty.io
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  sentry:
    git:
      url: https://github.com/lejard-h/sentry.git
      ref: web
  logging: ^0.11.0
  http: ^0.12.0

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.1.0