name: angular_sentry
description: Helper to implements sentry with Angular
version: 0.0.1
homepage: https://lefty.io
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  angular: ^4.0.0
  sentry_client: ^4.0.0
  stack_trace: ^1.9.0
  logging: ^0.11.0

#dev_dependencies:
#  test: ^0.12.0
