name: angular_sentry
description: Helper to implements sentry with Angular
version: 0.1.0

homepage: https://lefty.io
repository: https://github.com/leftyio/angular_sentry
issue_tracker: https://github.com/leftyio/angular_sentry/issues

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  angular: ^7.0.0
  sentry: ^6.0.0
  logging: ^1.0.0
  meta: ^1.1.0

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0
  lints: ^1.0.0
